name: SimpleTimber
version: '1.0'
main: com.github.K4RUNIO.simpleTimber.SimpleTimber
api-version: '1.21'
authors: [ Karunio ]
description: Simple plugin that will add Timber to your server!
commands:
  simpletimber:
    description: Reload the SimpleTimber configuration.
    usage: /simpletimber reload
    permission: simpletimber.reload